<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Symbols</title>
<style>body{font-family:Arial;margin:0;background:#f3f4f6;color:#111827}main{max-width:1400px;margin:0 auto;padding:24px}nav{margin-top:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav a{color:#2563eb;text-decoration:none}.auth-actions{margin-left:auto}.logout-btn{background:#111827;color:#fff;border:0;border-radius:6px;padding:6px 10px}.panel{margin-top:16px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:12px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}.card{border:1px solid #e5e7eb;border-radius:8px;padding:10px}.label{font-size:12px;color:#6b7280;text-transform:uppercase}.value{font-size:22px;font-weight:700}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e5e7eb;padding:8px 10px}th{background:#f9fafb;font-size:12px;text-transform:uppercase;color:#6b7280;white-space:nowrap}.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;font-weight:600}.green{background:#dcfce7;color:#166534}.red{background:#fee2e2;color:#991b1b}.gray{background:#e5e7eb;color:#374151}.nowrap{white-space:nowrap}</style></head><body><main>
<h1>Symbols</h1><p>Read-only symbol universe visibility.</p>
<nav><a href="{{ url('/admin/trade-setups') }}">Trade Setups</a><a href="{{ url('/admin/orders') }}">Orders</a><a href="{{ url('/admin/trades') }}">Trades</a><a href="{{ url('/admin/analytics') }}">Analytics</a><a href="{{ url('/admin/symbols') }}">Symbols</a><a href="{{ url('/admin/watchlist') }}">Watchlist</a><form class="auth-actions" method="POST" action="{{ url('/logout') }}">@csrf<button class="logout-btn" type="submit">Logout</button></form></nav>
<div class="panel"><form method="GET" action="{{ url('/admin/symbols') }}">Symbol <input type="text" name="symbol" value="{{ $filters['symbol'] }}"> Active <select name="active"><option value="all" @selected($filters['active']==='all')>All</option><option value="active" @selected($filters['active']==='active')>Active</option><option value="inactive" @selected($filters['active']==='inactive')>Inactive</option></select>
@if(in_array('source',$columns,true)) Source <select name="source"><option value="">All</option>@foreach($sources as $v)<option value="{{ $v }}" @selected($filters['source']===$v)>{{ $v }}</option>@endforeach</select>@endif
@if(in_array('exchange',$columns,true)) Exchange <select name="exchange"><option value="">All</option>@foreach($exchanges as $v)<option value="{{ $v }}" @selected($filters['exchange']===$v)>{{ $v }}</option>@endforeach</select>@endif
@if(in_array('last_seen_at',$columns,true)) Last seen from <input type="date" name="last_seen_from" value="{{ $filters['lastSeenFrom'] }}">@endif
Page size <select name="page_size">@foreach($pageSizes as $s)<option value="{{ $s }}" @selected($filters['pageSize']===$s)>{{ $s }}</option>@endforeach</select>
<button type="submit">Apply</button> <a href="{{ url('/admin/symbols') }}">Reset</a></form></div>
<div class="panel cards"><div class="card"><div class="label">Total</div><div class="value">{{ $stats['total'] }}</div></div><div class="card"><div class="label">Active</div><div class="value">{{ $stats['active'] ?? '—' }}</div></div><div class="card"><div class="label">Inactive</div><div class="value">{{ $stats['inactive'] ?? '—' }}</div></div><div class="card"><div class="label">Seen (7d)</div><div class="value">{{ $stats['recent_seen'] ?? '—' }}</div></div></div>
<div class="panel table-wrap"><table><thead><tr><th>ID</th><th>Symbol</th><th>Name</th><th>Exchange</th><th>Source</th><th>Is Active</th><th>Last Seen At</th><th>Created At</th><th>Updated At</th></tr></thead><tbody>
@forelse($rows as $r)<tr><td class="nowrap">{{ $r->id ?? '—' }}</td><td class="nowrap">{{ $r->symbol ?? '—' }}</td><td title="{{ $r->company_name ?? $r->security_name ?? '' }}">{{ \Illuminate\Support\Str::limit($r->company_name ?? $r->security_name ?? '—',60) }}</td><td>{{ $r->exchange ?? '—' }}</td><td>{{ $r->source ?? $r->source_type ?? '—' }}</td><td>@php($active=$r->is_active??null)<span class="badge {{ $active===1||$active===true?'green':(($active===0||$active===false)?'red':'gray') }}">{{ $active===1||$active===true?'active':(($active===0||$active===false)?'inactive':'—') }}</span></td><td class="nowrap">{{ $r->last_seen_at ?? '—' }}</td><td class="nowrap">{{ $r->created_at ?? '—' }}</td><td class="nowrap">{{ $r->updated_at ?? '—' }}</td></tr>
@empty<tr><td colspan="9">No records found for selected filters.</td></tr>@endforelse
</tbody></table><div style="margin-top:10px">{{ $rows->links() }}</div></div>
</main></body></html>
