<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Command Runs</title>
<style>body{font-family:Arial;margin:0;background:#f3f4f6;color:#111827}main{max-width:1500px;margin:0 auto;padding:24px}nav{margin-top:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav a{color:#2563eb;text-decoration:none}.auth-actions{margin-left:auto}.logout-btn{background:#111827;color:#fff;border:0;border-radius:6px;padding:6px 10px}.panel{margin-top:16px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:12px}.filters{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.filters label{display:flex;flex-direction:column;gap:4px;font-size:12px;color:#4b5563}.filters input,.filters select{min-height:30px;border:1px solid #d1d5db;border-radius:6px;padding:4px 8px}.filters button{min-height:32px;background:#2563eb;color:#fff;border:0;border-radius:6px;padding:0 12px}.filters a{color:#2563eb;text-decoration:none;padding-bottom:7px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e5e7eb;padding:8px 10px;vertical-align:top}th{background:#f9fafb;font-size:12px;text-transform:uppercase;color:#6b7280;white-space:nowrap}.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;font-weight:600}.green{background:#dcfce7;color:#166534}.red{background:#fee2e2;color:#991b1b}.blue{background:#dbeafe;color:#1e40af}.yellow{background:#fef3c7;color:#92400e}.gray{background:#e5e7eb;color:#374151}.nowrap{white-space:nowrap}.summary,.message{min-width:220px;max-width:420px}.muted{color:#6b7280}.sort-link{color:#2563eb;text-decoration:none}.details-link{color:#2563eb;text-decoration:none}.pagination{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-top:14px}.pagination-summary{color:#4b5563;font-size:14px}.pagination-links{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.pagination-link{display:inline-flex;align-items:center;justify-content:center;min-width:34px;height:34px;padding:0 10px;border:1px solid #d1d5db;border-radius:6px;background:#fff;color:#2563eb;text-decoration:none;font-size:14px}.pagination-link:hover{background:#eff6ff}.pagination-link.active{background:#2563eb;border-color:#2563eb;color:#fff;font-weight:700}.pagination-link.disabled{background:#f3f4f6;color:#9ca3af;cursor:not-allowed}.pagination-ellipsis{padding:0 4px;color:#6b7280}</style></head><body><main>
<h1>Command Runs</h1><p>Read-only command and workflow run history from the runs table.</p>
<nav><a href="{{ url('/admin/trade-setups') }}">Trade Setups</a><a href="{{ url('/admin/orders') }}">Orders</a><a href="{{ url('/admin/trades') }}">Trades</a><a href="{{ url('/admin/analytics') }}">Analytics</a><a href="{{ url('/admin/symbols') }}">Symbols</a><a href="{{ url('/admin/watchlist') }}">Watchlist</a><a href="{{ url('/admin/command-runs') }}">Command Runs</a><form class="auth-actions" method="POST" action="{{ url('/logout') }}">@csrf<button class="logout-btn" type="submit">Logout</button></form></nav>
<div class="panel"><form class="filters" method="GET" action="{{ url('/admin/command-runs') }}">
<label>Run Type <select name="run_type"><option value="">All</option>@foreach($runTypes as $v)<option value="{{ $v }}" @selected($filters['runType']===$v)>{{ $v }}</option>@endforeach</select></label>
<label>Status <select name="status"><option value="">All</option>@foreach($statuses as $v)<option value="{{ $v }}" @selected($filters['status']===$v)>{{ $v }}</option>@endforeach</select></label>
<label>From <input type="date" name="from" value="{{ $filters['from'] }}"></label>
<label>To <input type="date" name="to" value="{{ $filters['to'] }}"></label>
<label>Search <input type="text" name="search" value="{{ $filters['search'] }}" placeholder="run type, status, meta"></label>
<label>Has Error <select name="has_error"><option value="all" @selected($filters['hasError']==='all')>All</option><option value="yes" @selected($filters['hasError']==='yes')>Yes</option><option value="no" @selected($filters['hasError']==='no')>No</option></select></label>
<label>Page Size <select name="page_size">@foreach($pageSizes as $s)<option value="{{ $s }}" @selected($filters['pageSize']===$s)>{{ $s }}</option>@endforeach</select></label>
<button type="submit">Apply</button><a href="{{ url('/admin/command-runs') }}">Reset</a></form></div>
<div class="panel table-wrap"><table><thead><tr>@include('components.sortable-th',['label'=>'ID','sort'=>'id'])@if(in_array('run_type',$columns,true))@include('components.sortable-th',['label'=>'Run Type','sort'=>'run_type'])@endif @if(in_array('status',$columns,true))@include('components.sortable-th',['label'=>'Status','sort'=>'status'])@endif @if(in_array('started_at',$columns,true))@include('components.sortable-th',['label'=>'Started At','sort'=>'started_at'])@endif @if(in_array('completed_at',$columns,true))@include('components.sortable-th',['label'=>'Completed At','sort'=>'completed_at'])@endif<th>Duration</th><th>Summary</th><th>Error / Message</th>@if(in_array('created_at',$columns,true))<th>Created At</th>@endif @if(in_array('updated_at',$columns,true))<th>Updated At</th>@endif<th>Details</th></tr></thead><tbody>
@forelse($runs as $run)<tr><td class="nowrap">{{ $run->id ?? '—' }}</td>@if(in_array('run_type',$columns,true))<td class="nowrap">{{ $run->run_type ?? '—' }}</td>@endif @if(in_array('status',$columns,true))<td class="nowrap"><span class="{{ $run->status_badge_class }}">{{ $run->status ?? 'unknown' }}</span></td>@endif @if(in_array('started_at',$columns,true))<td class="nowrap">{{ $run->started_at ?? '—' }}</td>@endif @if(in_array('completed_at',$columns,true))<td class="nowrap">{{ $run->completed_at ?? '—' }}</td>@endif<td class="nowrap">{{ $run->duration }}</td><td class="summary">{{ $run->summary }}</td><td class="message">{{ $run->error_message }}</td>@if(in_array('created_at',$columns,true))<td class="nowrap">{{ $run->created_at ?? '—' }}</td>@endif @if(in_array('updated_at',$columns,true))<td class="nowrap">{{ $run->updated_at ?? '—' }}</td>@endif<td class="nowrap"><a class="details-link" href="{{ url('/admin/command-runs/'.$run->id) }}">View</a></td></tr>
@empty<tr><td colspan="{{ 5 + (in_array('run_type',$columns,true) ? 1 : 0) + (in_array('status',$columns,true) ? 1 : 0) + (in_array('started_at',$columns,true) ? 1 : 0) + (in_array('completed_at',$columns,true) ? 1 : 0) + (in_array('created_at',$columns,true) ? 1 : 0) + (in_array('updated_at',$columns,true) ? 1 : 0) }}">No command runs found for selected filters.</td></tr>@endforelse
</tbody></table>@include('admin.partials.pagination', ['paginator' => $runs])</div>
</main></body></html>
