<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Watchlist</title>
<style>body{font-family:Arial;margin:0;background:#f3f4f6;color:#111827}main{max-width:1500px;margin:0 auto;padding:24px}nav{margin-top:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav a{color:#2563eb;text-decoration:none}.auth-actions{margin-left:auto}.logout-btn{background:#111827;color:#fff;border:0;border-radius:6px;padding:6px 10px}.panel{margin-top:16px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:12px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}.card{border:1px solid #e5e7eb;border-radius:8px;padding:10px}.label{font-size:12px;color:#6b7280;text-transform:uppercase}.value{font-size:22px;font-weight:700}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e5e7eb;padding:8px 10px;vertical-align:top}th{background:#f9fafb;font-size:12px;text-transform:uppercase;color:#6b7280;white-space:nowrap}.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;font-weight:600}.green{background:#dcfce7;color:#166534}.red{background:#fee2e2;color:#991b1b}.orange{background:#ffedd5;color:#9a3412}.blue{background:#dbeafe;color:#1e3a8a}.gray{background:#e5e7eb;color:#374151}</style></head><body><main>
<h1>Watchlist Candidates</h1><p>Read-only visibility of weekend scan / refine candidates.</p>
<nav><a href="{{ url('/admin/trade-setups') }}">Trade Setups</a><a href="{{ url('/admin/orders') }}">Orders</a><a href="{{ url('/admin/trades') }}">Trades</a><a href="{{ url('/admin/analytics') }}">Analytics</a><a href="{{ url('/admin/symbols') }}">Symbols</a><a href="{{ url('/admin/watchlist') }}">Watchlist</a><form class="auth-actions" method="POST" action="{{ url('/logout') }}">@csrf<button class="logout-btn" type="submit">Logout</button></form></nav>
<div class="panel"><form method="GET" action="{{ url('/admin/watchlist') }}">Symbol <input name="symbol" value="{{ $filters['symbol'] }}">@if(in_array('status',$columns,true)) Status <select name="status"><option value="">All</option>@foreach($statuses as $v)<option value="{{ $v }}" @selected($filters['status']===$v)>{{ $v }}</option>@endforeach</select>@endif @if(in_array('setup_type',$columns,true)) Setup <select name="setup_type"><option value="">All</option>@foreach($setupTypes as $v)<option value="{{ $v }}" @selected($filters['setupType']===$v)>{{ $v }}</option>@endforeach</select>@endif @if(in_array('stage',$columns,true)) Stage <select name="stage"><option value="">All</option>@foreach($stages as $v)<option value="{{ $v }}" @selected($filters['stage']===$v)>{{ $v }}</option>@endforeach</select>@endif @if(in_array('score_total',$columns,true)) Min score <input type="number" step="0.001" name="min_score" value="{{ $filters['minScore'] }}">@endif @if(in_array('created_at',$columns,true)) From <input type="date" name="date_from" value="{{ $filters['dateFrom'] }}"> To <input type="date" name="date_to" value="{{ $filters['dateTo'] }}">@endif Page size <select name="page_size">@foreach($pageSizes as $s)<option value="{{ $s }}" @selected($filters['pageSize']===$s)>{{ $s }}</option>@endforeach</select><button type="submit">Apply</button> <a href="{{ url('/admin/watchlist') }}">Reset</a></form></div>
<div class="panel cards"><div class="card"><div class="label">Total</div><div class="value">{{ $stats['total'] }}</div></div><div class="card"><div class="label">Active/current</div><div class="value">{{ $stats['active'] ?? '—' }}</div></div><div class="card"><div class="label">Enter now</div><div class="value">{{ $stats['enter_now'] ?? '—' }}</div></div><div class="card"><div class="label">Removed/rejected/wait</div><div class="value">{{ $stats['rejected_wait'] ?? '—' }}</div></div><div class="card"><div class="label">Avg score</div><div class="value">{{ $stats['avg_score']!==null ? number_format($stats['avg_score'],3) : '—' }}</div></div></div>
<div class="panel table-wrap"><table><thead><tr><th>ID</th><th>Symbol</th><th>Status</th><th>Stage</th><th>Score</th><th>Setup Type</th><th>Trigger/Entry</th><th>Stop</th><th>Target</th><th>Reason</th><th>Created</th><th>Updated</th></tr></thead><tbody>@forelse($rows as $r)
@php($status = strtolower((string)($r->status ?? '')))
<tr><td>{{ $r->id ?? '—' }}</td><td>{{ $r->symbol_text ?? ('ID '.$r->symbol_id) }}</td><td><span class="badge {{ str_contains($status,'enter')||$status==='active'?'green':(str_contains($status,'reject')||str_contains($status,'remove')?'red':($status==='planned'||$status==='wait'?'blue':'gray')) }}">{{ $r->status ?? '—' }}</span></td><td>{{ $r->stage ?? '—' }}</td><td>{{ $r->score_total ?? $r->score ?? $r->rank ?? '—' }}</td><td>{{ $r->setup_type ?? '—' }}</td><td>{{ $r->trigger_price ?? $r->entry_price ?? '—' }}</td><td>{{ $r->stop_price ?? $r->support_low_price ?? '—' }}</td><td>{{ $r->target_price ?? $r->breakout_high_price ?? '—' }}</td><td title="{{ $r->reasoning_text ?? $r->notes ?? $r->summary ?? '' }}">{{ \\Illuminate\\Support\\Str::limit($r->reasoning_text ?? $r->notes ?? $r->summary ?? '—', 80) }}</td><td>{{ $r->created_at ?? '—' }}</td><td>{{ $r->updated_at ?? '—' }}</td></tr>
@empty<tr><td colspan="12">No records found for selected filters.</td></tr>@endforelse</tbody></table><div style="margin-top:10px">{{ $rows->links() }}</div></div>
</main></body></html>
