<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Analytics</title>
<style>body{font-family:Arial;margin:0;background:#f3f4f6;color:#111827}main{max-width:1400px;margin:0 auto;padding:24px}nav{margin-top:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav a{color:#2563eb;text-decoration:none}.auth-actions{margin-left:auto}.logout-btn{background:#111827;color:#fff;border:0;border-radius:6px;padding:6px 10px}.panel{margin-top:20px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:14px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.card{border:1px solid #e5e7eb;border-radius:8px;padding:10px}.label{font-size:12px;color:#6b7280;text-transform:uppercase}.value{font-size:22px;font-weight:700}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e5e7eb;padding:8px 10px}th{background:#f9fafb;font-size:12px;text-transform:uppercase;color:#6b7280}.text-green{color:#166534;font-weight:600}.text-red{color:#991b1b;font-weight:600}</style>
</head><body><main>
<h1>Analytics</h1><p>Read-only performance metrics for closed simulated trades.</p>
<nav><a href="{{ url('/admin/trade-setups') }}">Trade Setups</a><a href="{{ url('/admin/orders') }}">Orders</a><a href="{{ url('/admin/trades') }}">Trades</a><a href="{{ url('/admin/analytics') }}">Analytics</a>
            <a href="{{ url('/admin/symbols') }}">Symbols</a>
            <a href="{{ url('/admin/watchlist') }}">Watchlist</a><form class="auth-actions" method="POST" action="{{ url('/logout') }}">@csrf<button class="logout-btn" type="submit">Logout</button></form></nav>
<div class="panel"><form method="GET" action="{{ url('/admin/analytics') }}">From <input type="date" name="from" value="{{ request('from') }}"> To <input type="date" name="to" value="{{ request('to') }}"> Symbol <input type="text" name="symbol" value="{{ request('symbol') }}"> Setup <input type="text" name="setup_type" value="{{ request('setup_type') }}"> <button type="submit">Apply</button> <a href="{{ url('/admin/analytics') }}">Reset</a></form></div>
<div class="panel"><h2>Overall performance summary</h2><div class="cards">
@php($cards=[['Total closed trades',$summary['total_closed']],['Winning trades',$summary['wins']],['Losing trades',$summary['losses']],['Win rate %',number_format($summary['win_rate'],2).'%'],['Total PnL amount',number_format($summary['total_pnl_amount'],2)],['Average PnL %',number_format($summary['avg_pnl_percent'],2).'%'],['Average R multiple',number_format($summary['avg_r_multiple'],2)],['Best trade PnL %',$summary['best_pnl_percent']!==null?number_format($summary['best_pnl_percent'],2).'%':'—'],['Worst trade PnL %',$summary['worst_pnl_percent']!==null?number_format($summary['worst_pnl_percent'],2).'%':'—'],['Total TP hits',$summary['tp_hits']],['Total SL hits',$summary['sl_hits']]])
@foreach($cards as $c)<div class="card"><div class="label">{{ $c[0] }}</div><div class="value">{{ $c[1] }}</div></div>@endforeach
</div></div>
<div class="panel table-wrap"><h2>Recent closed trades</h2><table><thead><tr><th>Closed At</th><th>Symbol</th><th>Setup Type</th><th>Entry</th><th>Exit</th><th>Exit Reason</th><th>PnL %</th><th>PnL Amount</th><th>R Multiple</th><th>Review Verdict</th><th>Review Score</th></tr></thead><tbody>
@forelse($recentRows as $r)<tr><td>{{ $r['closed_at'] ?? '—' }}</td><td>{{ $r['symbol'] ?? '—' }}</td><td>{{ $r['setup_type'] ?? '—' }}</td><td>{{ $r['entry']!==null?number_format($r['entry'],4):'—' }}</td><td>{{ $r['exit']!==null?number_format($r['exit'],4):'—' }}</td><td class="{{ $r['exit_reason']==='target1_hit'?'text-green':($r['exit_reason']==='stop_loss_hit'?'text-red':'') }}">{{ $r['exit_reason'] ?? '—' }}</td><td class="{{ $r['pnl_percent']!==null?($r['pnl_percent']>=0?'text-green':'text-red'):'' }}">{{ $r['pnl_percent']!==null?number_format($r['pnl_percent'],2).'%':'—' }}</td><td class="{{ $r['pnl_amount']!==null?($r['pnl_amount']>=0?'text-green':'text-red'):'' }}">{{ $r['pnl_amount']!==null?number_format($r['pnl_amount'],2):'—' }}</td><td>{{ $r['r_multiple']!==null?number_format($r['r_multiple'],2):'—' }}</td><td>{{ $r['review_verdict'] ?? '—' }}</td><td>{{ $r['review_score'] ?? '—' }}</td></tr>
@empty<tr><td colspan="11">No closed simulated trades found.</td></tr>@endforelse
</tbody></table></div>
<div class="panel table-wrap"><h2>Performance by setup type</h2><table><thead><tr><th>Setup Type</th><th>Total Trades</th><th>Wins</th><th>Losses</th><th>Win Rate</th><th>Avg PnL %</th><th>Avg R Multiple</th></tr></thead><tbody>@forelse($bySetupType as $r)<tr><td>{{ $r['setup_type'] }}</td><td>{{ $r['total'] }}</td><td>{{ $r['wins'] }}</td><td>{{ $r['losses'] }}</td><td>{{ number_format($r['win_rate'],2) }}%</td><td>{{ number_format($r['avg_pnl_percent'],2) }}%</td><td>{{ number_format($r['avg_r_multiple'],2) }}</td></tr>@empty<tr><td colspan="7">No data.</td></tr>@endforelse</tbody></table></div>
<div class="panel table-wrap"><h2>Performance by symbol</h2><table><thead><tr><th>Symbol</th><th>Total Closed Trades</th><th>Wins</th><th>Losses</th><th>Win Rate</th><th>Total PnL Amount</th><th>Avg PnL %</th><th>Avg R Multiple</th></tr></thead><tbody>@forelse($bySymbol as $r)<tr><td>{{ $r['symbol'] }}</td><td>{{ $r['total'] }}</td><td>{{ $r['wins'] }}</td><td>{{ $r['losses'] }}</td><td>{{ number_format($r['win_rate'],2) }}%</td><td>{{ number_format($r['total_pnl_amount'],2) }}</td><td>{{ number_format($r['avg_pnl_percent'],2) }}%</td><td>{{ number_format($r['avg_r_multiple'],2) }}</td></tr>@empty<tr><td colspan="8">No data.</td></tr>@endforelse</tbody></table></div>
@if($reviewSummary!==null)<div class="panel"><h2>Prompt D review summary</h2><div class="cards">@foreach(['reviewed_count','avg_setup_quality_score','avg_entry_quality_score','avg_risk_reward_quality_score','prefer_similar','avoid_similar','neutral','needs_more_data'] as $k)<div class="card"><div class="label">{{ $k }}</div><div class="value">{{ is_numeric($reviewSummary[$k])?number_format($reviewSummary[$k],2):$reviewSummary[$k] }}</div></div>@endforeach</div></div>@endif
</main></body></html>
